server:
  port: 6996
spring:
  cloud:
    consul:
      discovery:
        hostname: 192.168.30.1
      host: 192.168.30.160
      port: 8500
  main:
    allow-bean-definition-overriding: true
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
swagger:
  base-package: com.allen.learningcloudclient.controller