spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    locations: db/facebook
    url: jdbc:mysql://127.0.0.1:3306/facebook?serverTimezone=GMT%2B8&characterEncoding=utf-8
    user: root
    password: root

learning:
  datasource:
    facebook:
      username: root
      password: root
      jdbc-url: jdbc:mysql://127.0.0.1:3306/facebook?serverTimezone=GMT%2B8&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
    google:
      username: root
      password: root
      jdbc-url: jdbc:mysql://127.0.0.1:3306/google?serverTimezone=GMT%2B8&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver