server:
  port: 6997
spring:
  application:
    name: learning-cloud-config-server
  cloud:
    consul:
      host: 192.168.30.160
      port: 8500
      discovery:
        hostname: 192.168.30.1
    config:
      server:
        git:
          uri: https://github.com/Allenjun/learning-cloud-config-server-repo.git
          password: d9863711h
          username: allenjun@gmail.com